#
spring.application.name=Blog
# JWT configuration
jwt.secret=9d8f3c6b1e5a7d2f4c8e1b9f6a3d7c2e9f4b6a1d8c3e5f7b
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
# Development credentials
spring.datasource.password=

#  JPA / HIBERNATE
# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Automatically update the database schema during development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


