#
spring.application.name=Blog
#To create the secret key
jwt.secret=your-256-bit-secret-key-here-make-it-at-least-32-bytes-long

#This is to manage the Database connection App is connecting to the  downloaded postgres DB instance
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
#Use only during the development not in production
spring.datasource.password=tayyabhafsa

#  JPA / HIBERNATE
#Use different Db every Db has diff sql dialect help in generating sql according to the Db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#To auto create the entities table and if any attribute  is added in it update it
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


